### ISSUE TITLE
Catch java.net.NoRouteToHostException for LightSwitchServer

### ISSUE THREAD

**Issue by matthew-bovolotto** [matthew-bovolotto/tp-link-message#1]
LightSwitchServer does not catch java.net.NoRouteToHostException and instead throws an exception and exits the program. Network outages should be caught, and logged to the user instead of exiting the program.

```
java.net.NoRouteToHostException: No route to host (Host unreachable)
        at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:400)
        at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:243)
        at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:225)
        at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:402)
        at java.base/java.net.Socket.connect(Socket.java:591)
        at java.base/java.net.Socket.connect(Socket.java:540)
        at java.base/java.net.Socket.<init>(Socket.java:436)
        at java.base/java.net.Socket.<init>(Socket.java:213)
        at commands.TpLinkMessage.getSystemInfo(TpLinkMessage.java:62)
        at commands.TpLinkMessage.getCommand(TpLinkMessage.java:44)
        at main.LightSwitchServer.messageAll(LightSwitchServer.java:84)
        at main.LightSwitchServer.stateChange(LightSwitchServer.java:66)
        at main.LightSwitchServer.main(LightSwitchServer.java:37)
Exception in thread "main" java.lang.NullPointerException
        at commands.TpLinkMessage.replaceZero(TpLinkMessage.java:56)
        at commands.TpLinkMessage.getCommand(TpLinkMessage.java:44)
        at main.LightSwitchServer.messageAll(LightSwitchServer.java:84)
        at main.LightSwitchServer.stateChange(LightSwitchServer.java:66)
        at main.LightSwitchServer.main(LightSwitchServer.java:37)
```

**Comment by matthew-bovolotto** [comment]
Catch for light switch poll added in commit: [83b57dc830438263111a6c301ced67624d553cbc](https://github.com/matthew-bovolotto/tp-link-message/commit/83b57dc830438263111a6c301ced67624d553cbc)
